services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - ENV=local
      - JWTKEY=localsecret
      - DB_URL=postgres://postgres:qwerty123@db:5432/task-tracker-db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=task-tracker-db
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 5