CREATE TABLE IF NOT EXISTS comments
(
    id SERIAL PRIMARY KEY,
    task_id INTEGER NOT NULL REFERENCES tasks(id),
    author_id INTEGER NOT NULL REFERENCES users(id),
    text TEXT NOT NULL,
    dateTime TIMESTAMP NOT NULL DEFAULT NOW()
);