server:
  host: localhost
  port: 8080
  auth_expire: 24h
  response_time: 100ms
  rps: 1000
  log_level: info
  async_hashing_limit: 10

db-conn:
  url: postgres://postgres:qwerty123@localhost:5432/task-tracker-db?sslmode=disable
  max_open_conns: 15